e2e test fails due to agent regexp being too strict
Error: For label key g.co/agent, value "opentelemetry-go 1.0.0-RC1; google-cloud-trace-exporter 1.0.0-RC1" did not match regex "opentelemetry-[\w-]+ [\d\.]+; [\w-]+ [\d\.]+"

Details: https://pantheon.corp.google.com/cloud-build/builds/a0e35716-89f6-46f4-93ff-76b7579726b8;step=1?project=opentelemetry-ops-e2e

BUG=191643395

Change-Id: Iecb6bd2e944bb187488eba4736a0084f11de364e